### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by felixlberg** [apostrophecms/apostrophe-rich-text-permalinks#11]
## To Reproduce

Step by step instructions to reproduce the behavior:

> 1. Install apostrophe-rich-text-permalinks and add it to app.js
> 2. Click 'Link" and choose 'Page'

## Expected behavior
> No error in console

## Describe the bug
```
(node:18735) UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/home/felix/github/material-cms/node_modules/apostrophe-rich-text-permalinks/views'
    at FSWatcher.start (internal/fs/watchers.js:210:26)
    at Object.watch (fs.js:1444:11)
    at createFsWatchInstance (/home/felix/github/material-cms/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/home/felix/github/material-cms/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/home/felix/github/material-cms/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleDir (/home/felix/github/material-cms/node_modules/chokidar/lib/nodefs-handler.js:559:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async NodeFsHandler._addToNodeFs (/home/felix/github/material-cms/node_modules/chokidar/lib/nodefs-handler.js:609:16)
    at async /home/felix/github/material-cms/node_modules/chokidar/index.js:445:21
    at async Promise.all (index 0)
(node:18735) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18735) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:18735) UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/home/felix/github/material-cms/node_modules/apostrophe-rich-text-permalinks/views/permalinkEditor.html'
    at FSWatcher.start (internal/fs/watchers.js:210:26)
    at Object.watch (fs.js:1444:11)
    at createFsWatchInstance (/home/felix/github/material-cms/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/home/felix/github/material-cms/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/home/felix/github/material-cms/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/home/felix/github/material-cms/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/home/felix/github/material-cms/node_modules/chokidar/lib/nodefs-handler.js:629:21)
(node:18735) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

```

## Details

**Version of Apostrophe:**
2.117.1

**Version of Node.js:**
v12.20.1

**Server Operating System:**
Ubuntu 20.04

**Additional context:**
```javascript
// lib/modules/apostrophe-rich-text-widgets/index.js
module.exports = {
  sanitizeHtml: {
    allowedTags: [
      'h2', 'h3', 'h4', 'p', 'a', 'ul', 'ol', 'li', 'strong', 'em', 'blockquote', 'iframe'
    ],
    allowedAttributes: {
      '*': ['style', 'class'],
      a: [ 'style', 'name', 'href', 'target', 'class' ]
    },
    allowedSchemes: ['http', 'https', 'ftp', 'mailto', 'tel']
  }
};
```

**Comment by felixlberg** [comment]
I was able to fix this problem, with adding:

```
// in app.js
modules: {
  'apostrophe-rich-text-widgets': {
    projection: {
      title: 1,
      _url: 1
    }
  }
}
```

It was as I thought cause mostly this watchers errors come from loading to much data in a join. 

But you should maybe change the documentation a little bit cause I thought It has a default `projection` but seems not so this need to added explicitly.

**Comment by abea** [comment]
@felixlberg Would that be on `apostrophe-rich-text-widgets` or `apostrophe-rich-text-permalinks`?

**Comment by felixlberg** [comment]
sry my fault I've copied that from this documentation but used `apostrophe-rich-text-permalinks` in my `app.js`

**Comment by abea** [comment]
The `title` and `_url` projection is included [by default](https://github.com/apostrophecms/apostrophe-rich-text-permalinks/blob/main/lib/modules/apostrophe-rich-text-permalinks-rich-text-widgets/index.js#L14-L17). Did you have any special configuration in the module when you got the error?
